version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: school_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_myschools
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school123
    ports:
      - '3307:3306' # Changed from 3306 to 3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./laravel_myschools.sql:/docker-entrypoint-initdb.d/laravel_myschools.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # Web Server (Apache + PHP)
  web:
    build: .
    container_name: school_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8082:80' # Changed from 8080 to 8082
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: laravel_myschools
      DB_USER: school_user
      DB_PASSWORD: school123

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: school_phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - '8083:80' # Changed from 8081 to 8083

volumes:
  mysql_data:
